name: app_final
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
    sdk: '>=3.1.5 <4.0.0'

dependencies:
    audioplayers: ^5.2.1
    firebase_core: ^2.24.0
    firebase_database: ^10.3.6
    flutter:
        sdk: flutter
    interactive_slider: ^0.2.1
    molten_navigationbar_flutter: ^1.0.1
    shared_preferences: ^2.2.2
    sleek_circular_slider: ^2.0.1
    slider_controller: ^0.0.5

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets\sounds\click_sound.wav
